# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/constrs_1/mdt_446.xdc

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/temac_10_100_1000.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==temac_10_100_1000 || ORIG_REF_NAME==temac_10_100_1000}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/icmp_payload_buffer/icmp_payload_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==icmp_payload_buffer || ORIG_REF_NAME==icmp_payload_buffer}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/vmm_conf_buffer/vmm_conf_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vmm_conf_buffer || ORIG_REF_NAME==vmm_conf_buffer}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/readout_fifo/readout_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==readout_fifo || ORIG_REF_NAME==readout_fifo}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_readout/ila_readout.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_readout || ORIG_REF_NAME==ila_readout}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/packet_len_fifo/packet_len_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==packet_len_fifo || ORIG_REF_NAME==packet_len_fifo}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_quad_spi_0 || ORIG_REF_NAME==axi_quad_spi_0}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_top_level/ila_top_level.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_top_level || ORIG_REF_NAME==ila_top_level}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_200_to_400 || ORIG_REF_NAME==clk_wiz_200_to_400}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_low_jitter || ORIG_REF_NAME==clk_wiz_low_jitter}]

# IP: /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0}]
