# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/MDT_446/MDT_446.cache/wt [current_project]
set_property parent.project_path /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/MDT_446/MDT_446.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/MDT_446/MDT_446.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/xadc/xadc_read.v
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/xadc/xadc.v
}
read_vhdl -library xil_defaultlib {
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/axi.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp_types.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/ipv4_types.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp_REQ.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp_RX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp_STORE_br.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp_SYNC.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/IPv4_RX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp_TX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/IPv4_TX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/common/temac_10_100_1000_sync_block.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arp.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/tx_arbitrator.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/arpv2.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/IPv4.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/fifo/temac_10_100_1000_rx_client_fifo.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/fifo/temac_10_100_1000_tx_client_fifo.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/configuration/fpga_config_block.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/configuration/vmm_config_block.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/IP_complete_nomac.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/ICMP_RX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/ICMP_TX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/ping_reply_processor.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/icmp_udp_mux.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/UDP_RX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/UDP_TX.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/temac_10_100_1000_block.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/fifo/temac_10_100_1000_ten_100_1g_eth_fifo.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/common/temac_10_100_1000_reset_sync.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/CDCC.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/vmmSignalsDemux.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/configuration/udp_data_in_handler.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/configuration/select_vmm.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/configuration/axi_quad_top.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/temac_10_100_1000_config_vector_sm.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/UDP_ICMP_Complete_nomac.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/i2c_top.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/imports/sgmii_10_100_1000/ipcore_dir/temac_10_100_1000/example_design/temac_10_100_1000_fifo_block.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/event_timing_reset.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/select_data.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/FIFO2UDP.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/trigger.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/packet_formation.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/readout/vmm_readout.vhd
  /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/mmfe8_top.vhd
}
read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/temac_10_100_1000.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/synth/temac_10_100_1000_board.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/synth/temac_10_100_1000.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/synth/temac_10_100_1000_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/synth/temac_10_100_1000_clocks.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/temac_10_100_1000/temac_10_100_1000.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/icmp_payload_buffer/icmp_payload_buffer.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/icmp_payload_buffer/icmp_payload_buffer/icmp_payload_buffer.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/icmp_payload_buffer/icmp_payload_buffer/icmp_payload_buffer_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/icmp_payload_buffer/icmp_payload_buffer_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/icmp_payload_buffer/icmp_payload_buffer.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/vmm_conf_buffer/vmm_conf_buffer.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/vmm_conf_buffer/vmm_conf_buffer/vmm_conf_buffer.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/vmm_conf_buffer/vmm_conf_buffer/vmm_conf_buffer_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/vmm_conf_buffer/vmm_conf_buffer_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/vmm_conf_buffer/vmm_conf_buffer.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/readout_fifo/readout_fifo.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/readout_fifo/readout_fifo/readout_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/readout_fifo/readout_fifo_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/readout_fifo/readout_fifo.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_readout/ila_readout.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_readout/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_readout/ila_readout_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_readout/ila_readout.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/packet_len_fifo/packet_len_fifo.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/packet_len_fifo/packet_len_fifo/packet_len_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/packet_len_fifo/packet_len_fifo_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/packet_len_fifo/packet_len_fifo.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_clocks.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_top_level/ila_top_level.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_top_level/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_top_level/ila_top_level_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/ila_top_level/ila_top_level.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400_board.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400_late.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter_board.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter_late.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xci]

read_ip -quiet /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]
set_property is_locked true [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/constrs_1/mdt_446.xdc
set_property used_in_implementation false [get_files /home/pmoschov/myGitRepos/atlas-nsw-mmfe8-firmware/sources/constrs_1/mdt_446.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mmfe8_top -part xc7a200tfbg484-2


write_checkpoint -force -noxdef mmfe8_top.dcp

catch { report_utilization -file mmfe8_top_utilization_synth.rpt -pb mmfe8_top_utilization_synth.pb }
